### ISSUE TITLE
Buy Menu non-responsive

### ISSUE THREAD

**Issue by ReyZu** [Ochii/cso2-master-server#10]
When playing TDM and your character dies, the buy menu doesn't respond after bringing it up (B key).

You cannot buy any weapons and the menu is simply empty. 

Cannot exit too. Buttons do not respond. Menu only disappears once you respawn.

**Comment by DebugBios** [comment]
![cso2_0008](https://user-images.githubusercontent.com/44349391/49700345-c2135500-fc20-11e8-93bc-17c0a46de42d.jpg)
Items must be added to inventory to change weapons and character.

**Comment by leang97** [comment]
> I think that data is handled by Packet_Inventory, if anyone wants to have a look at it

I am not a nodejs and typescript coder, but I take a look at the source code for master server anyway, the Master Server Code itself doesn't handle the packet for Inventory yet, that's why its empty. I still have no idea how the master server worked with packets and how it responds, etc, will need more guidance and how the packet worked and how do we know what packet to reply in the first place anyway, we can't just snatch the packet from the official server since it was down.
