### ISSUE TITLE
How do I change a bot's player model?

### ISSUE THREAD

**Issue by rizkidewanto** [Ochii/cso2-master-server#78]
Is it able to change the bot skin? Seems to be boring with same bot skin. Thank you

**Comment by awsl1** [comment]
Try modifying BotProfile.db "Skin".

**Comment by rizkidewanto** [comment]
Where is it? I try to open it using UnCSO2 but didn't found the file

**Comment by DebugBios** [comment]
@rizkidewanto scripts

**Comment by rizkidewanto** [comment]
@DebugBios Find it, thanks. And how I know which model to replace? I mean like model list

**Comment by reina45** [comment]
Since OP didn't update with how-to, here's how-to: 
Character list can be found at `Data/cstrike/scripts/characters.csv`, I grouped CT and TR model ID below (botprofile uses 1 - 28).

![characters dot csv](https://github.com/user-attachments/assets/7ee0ddb1-e7b0-4aed-809d-852cebe84b4a)

Replace Skin = x of each bot according to classid as in screenshot (I used "Skin = ." in Notepad++ to replace easier; in testing Elite didn't seem to correspond to Elite level bot so probably it's using a specific difficulty)

Sample:
![cso2_0011](https://github.com/user-attachments/assets/7c288b30-2212-4301-a705-d8d31bbce5c1)

Attached is botprofile.db that use all 28 bots for convenience. 

[botprofile.zip](https://github.com/user-attachments/files/18232530/botprofile.zip)
