### ISSUE TITLE
Request additional item

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#84]
"CSO2_ITEM_NAME_PROFILEFRAME_00"		"영예의 부사관"

"CSO2_ITEM_NAME_PROFILEFRAME_01"		"영예의 위관장교"

"CSO2_ITEM_NAME_PROFILEFRAME_02"		"영예의 영관장교"

"CSO2_ITEM_NAME_PROFILEFRAME_03"		"최고영예의 장군"

"CSO2_ITEM_NAME_VIPCARD"		"VIP회원권"

"CSO2_ITEM_NAME_HIDEMODE_ACTION_001"		"액션팩 1탄"

**Comment by dounai2333** [comment]
personal information borders don't apply proactively, they are a passive item, and you can still get a border without items
![7UD5A3B()P)YTIE5O5Y3RDR](https://user-images.githubusercontent.com/45044404/56089205-45d89900-5ec2-11e9-9b17-946f001bc0fb.png)

VIP privilege card are useless because you can still get a VIP bonus even if you don't have item (although you may not feel it), and the current randomization mechanism might cause you to get VIP0 after you log into the game (i.e., no VIP :P)
action card are also no needed, they currently works without this specific item.

if you expect VIP card and action item, just add two lines of code to userinventory (id: 2017, 3001)
and, it doesn't make sense to call out a profile border in your inventory, because it doesn't really apply to your profile right now, but if you want to get it, you can get it by modifying unk05 in fulluserupdate, GL. (solve problems by yourself always brings happiness and a sense of achievement, don't you?)

**Comment by DebugBios** [comment]
@dounai2333 Does it mean that active item does not apply? ex.Action Pack,Profile Border
